# Banking Fraud & Risk Analytics Platform

## Objective

The objective of this notebook is to understand the structure of the dataset before performing any cleaning or analysis.

This notebook covers:

- Loading the datasets
- Inspecting the data
- Understanding data types
- Reviewing dataset dimensions
- Identifying relationships between datasets

### Importing All Required Libraries

In [1]:
#Libraries
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

### Loading the Dataset

In [4]:
accounts = pd.read_csv("../data/raw/accounts.csv")
transactions = pd.read_csv("../data/raw/Trans.csv")

#### First View of accounts and transaction dataset

In [5]:
accounts.head()

,Bank Name,Bank ID,Account Number,Entity ID,Entity Name
0,Portugal Bank #4507,331579,80B779D80,80062E240,Sole Proprietorship #50438
1,Canada Bank #27,210,809D86900,800C998A0,Corporation #33520
2,UK Bank #33,21884,80812BE00,800C47F50,Partnership #35397
3,Germany Bank #4815,32742,81047F300,80096F0B0,Corporation #48813
4,National Bank of Harrisburg,127390,80BD8CF00,800FB8760,Corporation #889

In [6]:
transactions.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

#### Shape of datasets

In [9]:
print("Account shape :", accounts.shape)
print("Tanscations shape :",transactions.shape)

Account shape : (518581, 5)
Tanscations shape : (5078345, 11)

#### Information of Dataset

In [ ]:
print("Account Information :",accounts.info())

<class 'pandas.DataFrame'>
RangeIndex: 518581 entries, 0 to 518580
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Bank Name       518581 non-null  str
 1   Bank ID         518581 non-null  int64
 2   Account Number  518581 non-null  str
 3   Entity ID       518581 non-null  str
 4   Entity Name     518581 non-null  str
dtypes: int64(1), str(4)
memory usage: 47.3 MB
Account Information : None

In [14]:
print("transaction information :",transactions.info())

<class 'pandas.DataFrame'>
RangeIndex: 5078345 entries, 0 to 5078344
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Timestamp           str
 1   From Bank           int64
 2   Account             str
 3   To Bank             int64
 4   Account.1           str
 5   Amount Received     float64
 6   Receiving Currency  str
 7   Amount Paid         float64
 8   Payment Currency    str
 9   Payment Format      str
 10  Is Laundering       int64
dtypes: float64(2), int64(3), str(6)
memory usage: 699.6 MB
transaction information : None

## 📄 Column Descriptions (Accounts Dataset)

**Bank Name:** Name of the financial institution where the account is maintained.

**Bank ID:** Unique numerical identifier assigned to each bank.

**Account Number:** Unique identifier representing a customer's bank account within a bank.

**Entity ID:** Unique identifier assigned to the account holder (individual or organization).

**Entity Name:** Name of the account owner or business entity, such as a Corporation, Partnership, or Sole Proprietorship.

## 📄 Column Descriptions (Transactions Dataset)

**Timestamp:** Date and time when the transaction was initiated.

**From Bank:** Unique identifier of the bank sending the funds.

**Account:** Account number of the sender initiating the transaction.

**To Bank:** Unique identifier of the bank receiving the funds.

**Account.1:** Account number of the recipient receiving the transaction.

**Amount Received:** Amount credited to the recipient's account in the receiving currency.

**Receiving Currency:** Currency in which the recipient receives the funds.

**Amount Paid:** Amount debited from the sender's account in the payment currency.

**Payment Currency:** Currency used by the sender to make the payment.

**Payment Format:** Method or channel through which the transaction was processed (e.g., Cheque, Reinvestment, Credit Card, Cash, Wire Transfer).

**Is Laundering:** Binary target variable indicating whether the transaction is associated with money laundering.
- **0:** Legitimate Transaction
- **1:** Suspicious / Money Laundering Transaction

## Statastical Information

In [17]:
accounts.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Bank Name,518581,20053,National Bank of Laramie,3797,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bank ID,518581.0,NaN,NaN,NaN,103425.510831,121479.549761,1.0,11107.0,32014.0,217096.0,356303.0
Account Number,518581,518573,80A7FDE00,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Entity ID,518581,166207,800DB93F0,7820,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Entity Name,518581,166207,Corporation #34854,7820,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
transactions.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Timestamp,5078345,15018,2022/09/01 00:04,11193,NaN,NaN,NaN,NaN,NaN,NaN,NaN
From Bank,5078345.0,NaN,NaN,NaN,45730.565729,81765.622281,1.0,119.0,9679.0,28628.0,356303.0
Account,5078345,496995,100428660,168672,NaN,NaN,NaN,NaN,NaN,NaN,NaN
To Bank,5078345.0,NaN,NaN,NaN,65744.562853,84092.990137,1.0,4259.0,21568.0,122332.0,356294.0
Account.1,5078345,420636,100428660,1084,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Amount Received,5078345.0,NaN,NaN,NaN,5988726.070073,1037183108.891989,0.000001,183.37,1411.01,12346.27,1046302363293.47998
Receiving Currency,5078345,15,US Dollar,1879341,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Amount Paid,5078345.0,NaN,NaN,NaN,4509273.367741,869772830.919865,0.000001,184.48,1414.54,12297.84,1046302363293.47998
Payment Currency,5078345,15,US Dollar,1895172,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Format,5078345,7,Cheque,1864331,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Is Laundering,5078345.0,NaN,NaN,NaN,0.001019,0.031912,0.0,0.0,0.0,0.0,1.0

## Missing Values

In [19]:
accounts.isnull().sum()

Bank Name         0
Bank ID           0
Account Number    0
Entity ID         0
Entity Name       0
dtype: int64

In [20]:
transactions.isna().sum()

Timestamp             0
From Bank             0
Account               0
To Bank               0
Account.1             0
Amount Received       0
Receiving Currency    0
Amount Paid           0
Payment Currency      0
Payment Format        0
Is Laundering         0
dtype: int64

## Duplicate Values

In [21]:
accounts.duplicated().sum()

np.int64(0)

In [22]:
transactions.duplicated().sum()

np.int64(9)

# Initial Observations

- Successfully loaded both datasets.
- Reviewed dataset dimensions.
- Identified column names and data types.
- Checked for duplicate records.
- Checked for missing values.
- Data is ready for detailed quality assessment.