# Banking Fraud & Risk Analytics Platform

### Objective

The objective of this notebook is to evaluate the quality of the Accounts and Transactions datasets before performing any data cleaning or feature engineering.

The assessment focuses on:
- Data types
- Unique values
- Outliers
- Business rule validation
- Overall data quality

## Importing All Required Libraries

In [2]:
#Libraries
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

## Loading Datasets

In [3]:
accounts = pd.read_csv("../data/raw/accounts.csv")
transactions = pd.read_csv("../data/raw/Trans.csv")

### DataType Validation

In [5]:
accounts.dtypes

Bank Name           str
Bank ID           int64
Account Number      str
Entity ID           str
Entity Name         str
dtype: object

In [6]:
transactions.dtypes

Timestamp                 str
From Bank               int64
Account                   str
To Bank                 int64
Account.1                 str
Amount Received       float64
Receiving Currency        str
Amount Paid           float64
Payment Currency          str
Payment Format            str
Is Laundering           int64
dtype: object

## Unique Values

In [7]:
accounts.nunique()

Bank Name          20053
Bank ID            30470
Account Number    518573
Entity ID         166207
Entity Name       166207
dtype: int64

In [8]:
transactions.nunique()

Timestamp              15018
From Bank              30470
Account               496995
To Bank                15811
Account.1             420636
Amount Received       915161
Receiving Currency        15
Amount Paid           923873
Payment Currency          15
Payment Format             7
Is Laundering              2
dtype: int64

## Outlier Detection

In [13]:
accounts.describe().T

,count,mean,std,min,25%,50%,75%,max
Bank ID,518581.0,103425.510831,121479.549761,1.0,11107.0,32014.0,217096.0,356303.0

In [14]:
transactions.describe().T

,count,mean,std,min,25%,50%,75%,max
From Bank,5078345.0,4.573057e+04,8.176562e+04,1.000000,119.00,9679.00,28628.00,3.563030e+05
To Bank,5078345.0,6.574456e+04,8.409299e+04,1.000000,4259.00,21568.00,122332.00,3.562940e+05
Amount Received,5078345.0,5.988726e+06,1.037183e+09,0.000001,183.37,1411.01,12346.27,1.046302e+12
Amount Paid,5078345.0,4.509273e+06,8.697728e+08,0.000001,184.48,1414.54,12297.84,1.046302e+12
Is Laundering,5078345.0,1.019427e-03,3.191219e-02,0.000000,0.00,0.00,0.00,1.000000e+00

## Business Rule Validation

In [17]:
#Negative Amounts paid
(transactions["Amount Paid"] < 0).sum()

np.int64(0)

In [20]:
#Negative Amounts Received
(transactions["Amount Received"] < 0).sum()

np.int64(0)

## Invalid Bank IDs

In [21]:
transactions["From Bank"].isnull().sum()

np.int64(0)

In [22]:
transactions["To Bank"].isnull().sum()

np.int64(0)

## Laundering Values

In [23]:
transactions["Is Laundering"].value_counts()

Is Laundering
0    5073168
1       5177
Name: count, dtype: int64

## Currency Validation

In [24]:
transactions["Payment Currency"].unique()

<ArrowStringArray>
[        'US Dollar',           'Bitcoin',              'Euro',
 'Australian Dollar',              'Yuan',             'Rupee',
               'Yen',      'Mexican Peso',          'UK Pound',
             'Ruble',   'Canadian Dollar',       'Swiss Franc',
       'Brazil Real',       'Saudi Riyal',            'Shekel']
Length: 15, dtype: str

In [25]:
transactions["Receiving Currency"].unique()

<ArrowStringArray>
[        'US Dollar',           'Bitcoin',              'Euro',
 'Australian Dollar',              'Yuan',             'Rupee',
      'Mexican Peso',               'Yen',          'UK Pound',
             'Ruble',   'Canadian Dollar',       'Swiss Franc',
       'Brazil Real',       'Saudi Riyal',            'Shekel']
Length: 15, dtype: str

## Payment Format

In [26]:
transactions["Payment Format"].value_counts()

Payment Format
Cheque          1864331
Credit Card     1323324
ACH              600797
Cash             490891
Reinvestment     481056
Wire             171855
Bitcoin          146091
Name: count, dtype: int64

## Key Findings

- No missing values detected.
- Duplicate analysis completed.
- Data types validated.
- Business rules verified.
- Dataset is suitable for cleaning and feature engineering.