# Banking Fraud & Risk Analytics Platform

## Importing All Required Libraries

In [20]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

plt.style.use("ggplot")

sns.set_theme(style="whitegrid")

%matplotlib inline

# Section 1: Data Overview

## Loading the Dataset

In [21]:
transactions = pd.read_csv("../data/processed/cleaned_transaction.csv")

accounts = pd.read_csv("../data/processed/cleaned_accounts.csv")

In [22]:
#Changing the dtype
transactions["timestamp"] = pd.to_datetime(
    transactions["timestamp"]
)

## Creating the copies of dataset

In [23]:
transactions_eda = transactions.copy()

accounts_eda = accounts.copy()

## Dataset Overview

Before beginning the exploratory analysis, the datasets are loaded and inspected to understand their structure, dimensions, data types, and overall characteristics.

## Dataset Shape

In [25]:
print("Transactions Shape :", transactions_eda.shape)

print("Accounts Shape :", accounts_eda.shape)

Transactions Shape : (5078336, 11)
Accounts Shape : (518581, 5)

In [27]:
#Dataset information
transactions_eda.info()
print("--"*50)
accounts_eda.info()

<class 'pandas.DataFrame'>
RangeIndex: 5078336 entries, 0 to 5078335
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   timestamp           datetime64[us]
 1   from_bank           int64
 2   sender_account      str
 3   to_bank             int64
 4   receiver_account    str
 5   amount_received     float64
 6   receiving_currency  str
 7   amount_paid         float64
 8   payment_currency    str
 9   payment_format      str
 10  is_laundering       int64
dtypes: datetime64[us](1), float64(2), int64(3), str(5)
memory usage: 622.1 MB
----------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 518581 entries, 0 to 518580
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   bank_name       518581 non-null  str
 1   bank_id         518581 non-null  int64
 2   account_number  518581 non-null  str
 3   entity_id       518581 non-null  str
 4   entity_name     518581 non-null  str
dtypes: int64(1), str(4)
memory usage: 47.3 MB

In [30]:
#Statistical Summary
transactions_eda.describe().T

,count,mean,min,25%,50%,75%,max,std
timestamp,5078336,2022-09-05 07:16:07.855403,2022-09-01 00:00:00,2022-09-02 04:32:00,2022-09-05 12:16:00,2022-09-08 03:13:00,2022-09-18 16:18:00,NaN
from_bank,5078336.0,45730.583254,1.0,119.0,9679.0,28628.0,356303.0,81765.6744
to_bank,5078336.0,65744.609435,1.0,4259.0,21568.0,122332.0,356294.0,84093.026783
amount_received,5078336.0,5988736.683497,0.000001,183.37,1411.04,12346.3,1046302363293.47998,1037184027.926735
amount_paid,5078336.0,4509281.359229,0.000001,184.48,1414.57,12298.15,1046302363293.47998,869773601.619475
is_laundering,5078336.0,0.001019,0.0,0.0,0.0,0.0,1.0,0.031912

In [31]:
accounts_eda.describe().T

,count,mean,std,min,25%,50%,75%,max
bank_id,518581.0,103425.510831,121479.549761,1.0,11107.0,32014.0,217096.0,356303.0

In [ ]:
#Missing Values
transactions_eda.isnull().sum()

bank_name         0
bank_id           0
account_number    0
entity_id         0
entity_name       0
dtype: int64

In [34]:
#Missing Values
accounts_eda.isnull().sum()

bank_name         0
bank_id           0
account_number    0
entity_id         0
entity_name       0
dtype: int64

In [ ]:
#Duplicate Values
transactions_eda.duplicated().sum()

np.int64(0)

In [37]:
#Duplicate Values
accounts_eda.duplicated().sum()

np.int64(0)

## Initial Observations

- The Transactions dataset contains over **5 million** financial transactions.
- The Accounts dataset contains over **500 thousand** customer accounts.
- No missing values were detected.
- Duplicate transaction records were removed during the data cleaning phase.
- The datasets are ready for exploratory analysis.

# Section 2: Univariate Analysis